# Preliminary Exploration Notebook

In [2]:
import pandas as pd
import numpy as np

In [3]:
school_data = pd.read_csv("data/CRDC 2015-16 School Data.csv", encoding = "ISO-8859-1")
school_layout = pd.read_csv("data/CRDC 2015-16 School Data Record Layout.csv", encoding = "ISO-8859-1")

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (2,6,23,24,25,30,31,1828) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
school_data.head()

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,COMBOKEY,JJ,SCH_GRADE_PS,SCH_GRADE_KG,...,SCH_FTESERVICES_PSY,SCH_FTESERVICES_SOC,SCH_JJTYPE,SCH_JJSYDAYS,SCH_JJHOURS,SCH_JJPART_LT15,SCH_JJPART_15T30,SCH_JJPART_31T90,SCH_JJPART_91T180,SCH_JJPART_OV180
0,AL,ALABAMA,100002,Alabama Youth Services,1705,Wallace Sch - Mt Meigs Campus,10000201705,Yes,No,No,...,2.0,0.0,-7,-7,-7,-7,-7,-7,-7,-7
1,AL,ALABAMA,100002,Alabama Youth Services,1706,McNeel Sch - Vacca Campus,10000201706,Yes,No,No,...,1.0,0.0,-7,-7,-7,-7,-7,-7,-7,-7
2,AL,ALABAMA,100002,Alabama Youth Services,1876,Alabama Youth Services,10000201876,No,No,No,...,0.0,0.0,-9,-9,-9,-9,-9,-9,-9,-9
3,AL,ALABAMA,100002,Alabama Youth Services,99995,AUTAUGA CAMPUS,10000299995,Yes,No,No,...,0.0,0.0,-7,-7,-7,-7,-7,-7,-7,-7
4,AL,ALABAMA,100005,Albertville City,870,Albertville Middle School,10000500870,No,No,No,...,0.0,0.0,-9,-9,-9,-9,-9,-9,-9,-9

In [39]:
pd.set_option("display.max_rows", 122)
school_data[school_data['SCH_NAME']== 'Severna Park High']

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,COMBOKEY,JJ,SCH_GRADE_PS,SCH_GRADE_KG,...,SCH_FTESERVICES_PSY,SCH_FTESERVICES_SOC,SCH_JJTYPE,SCH_JJSYDAYS,SCH_JJHOURS,SCH_JJPART_LT15,SCH_JJPART_15T30,SCH_JJPART_31T90,SCH_JJPART_91T180,SCH_JJPART_OV180
38196,MD,MARYLAND,2400060,Anne Arundel County Public Schools,127,Severna Park High,2.40006e+11,No,No,No,...,1.0,0.0,-9,-9,-9,-9,-9,-9,-9,-9

In [6]:
school_layout[school_layout["Field_Name"] == "SCH_JJHOURS"]["Field_Description"]

1830    Justice Facility Educational Program Hours per...
Name: Field_Description, dtype: object

In [7]:
school_layout

,Order,Excel_Column_Finder,Field_Name,Field_Description,Module
0,1,A,LEA_STATE,District State Abbreviation,Identification
1,2,B,LEA_STATE_NAME,District State Name,Identification
2,3,C,LEAID,7 Digit LEAID District Identification Code,Identification
3,4,D,LEA_NAME,District Name,Identification
4,5,E,SCHID,5 Digit School Identification Code,Identification
5,6,F,SCH_NAME,School Name,Identification
6,7,G,COMBOKEY,7 Digit LEAID District Identification Code+5 D...,Identification
7,8,H,JJ,"Juvenile Justice Facility: ""Yes"" indicates a l...",Identification
8,9,I,SCH_GRADE_PS,Grades with Students Enrolled: Preschool,School Characteristics
9,10,J,SCH_GRADE_KG,Grades with Students Enrolled: Kindergarten,School Characteristics
10,11,K,SCH_GRADE_G01,Grades with Students Enrolled: Grade 1,School Characteristics
11,12,L,SCH_GRADE_G02,Grades with Students Enrolled: Grade 2,School Characteristics
12,13,M,SCH_GRADE_G03,Grades with Students Enrolled: Grade 3,School Characteristics
13,14,N,SCH_GRADE_G04,Grades with Students Enrolled: Grade 4,School Characteristics
14,15,O,SCH_GRADE_G05,Grades with Students Enrolled: Grade 5,School Characteristics
15,16,P,SCH_GRADE_G06,Grades with Students Enrolled: Grade 6,School Characteristics
16,17,Q,SCH_GRADE_G07,Grades with Students Enrolled: Grade 7,School Characteristics
17,18,R,SCH_GRADE_G08,Grades with Students Enrolled: Grade 8,School Characteristics
18,19,S,SCH_GRADE_G09,Grades with Students Enrolled: Grade 9,School Characteristics
19,20,T,SCH_GRADE_G10,Grades with Students Enrolled: Grade 10,School Characteristics
20,21,U,SCH_GRADE_G11,Grades with Students Enrolled: Grade 11,School Characteristics
21,22,V,SCH_GRADE_G12,Grades with Students Enrolled: Grade 12,School Characteristics
22,23,W,SCH_GRADE_UG,Grades with Students Enrolled: Ungraded,School Characteristics
23,24,X,SCH_UGDETAIL_ES,Ungraded Detail: Elementary school age students,School Characteristics
24,25,Y,SCH_UGDETAIL_MS,Ungraded Detail: Middle school age students,School Characteristics
25,26,Z,SCH_UGDETAIL_HS,Ungraded Detail: High school age students,School Characteristics
26,27,AA,SCH_STATUS_SPED,School Characteristics: Special education school,School Characteristics
27,28,AB,SCH_STATUS_MAGNET,School Characteristics: Magnet school or schoo...,School Characteristics
28,29,AC,SCH_STATUS_CHARTER,School Characteristics: Charter school,School Characteristics
29,30,AD,SCH_STATUS_ALT,School Characteristics: Alternative school,School Characteristics
...,...,...,...,...,...
1806,1807,BQM,SCH_FTE_AID_WFED,Full-time Equivalency Count of Instructional A...,School Expenditures
1807,1808,BQN,SCH_SAL_AID_WFED,Salary Expenditures for Instructional Aides Fu...,School Expenditures
1808,1809,BQO,SCH_FTE_SUP_WFED,Full-time Equivalency Count of Support Service...,School Expenditures
1809,1810,BQP,SCH_SAL_SUP_WFED,Salary Expenditures for Support Services Staff...,School Expenditures
1810,1811,BQQ,SCH_FTE_ADM_WFED,Full-time Equivalency Count of School Administ...,School Expenditures
1811,1812,BQR,SCH_SAL_ADM_WFED,Salary Expenditures for School Administration...,School Expenditures
1812,1813,BQS,SCH_SAL_TOTPERS_WFED,Salary Expenditures for Total Personnel (instr...,School Expenditures
1813,1814,BQT,SCH_NPE_WFED,Amount of Non-Personnel Expenditures Associate...,School Expenditures
1814,1815,BQU,SCH_FTETEACH_TOT,Total FTE of Teachers,School Support
1815,1816,BQV,SCH_FTETEACH_CERT,Number of FTE teachers who are certified,School Support
1816,1817,BQW,SCH_FTETEACH_NOTCERT,Number of FTE teachers who are not certified,School Support
1817,1818,BQX,SCH_FTETEACH_FY,Number of FTE teachers in their first year of ...,School Support
1818,1819,BQY,SCH_FTETEACH_SY,Number of FTE teachers in their second year of...,School Support
1819,1820,BQZ,SCH_TEACHERS_CURR_TOT,Number of current school year teachers,School Support
1820,1821,BRA,SCH_TEACHERS_PREV_TOT,Number of previous school year teachers,School Support
1821,1822,BRB,SCH_FTECOUNSELORS,Number of FTE school counselors,School Support
1822,1823,BRC,SCH_FTETEACH_ABSENT,Number of FTE teachers who were absent more th...,School Support
1823,1824,BRD,SCH_FTESECURITY_LEO,Number of FTE sworn law enforcement officers,School Support
1824,1825,BRE,SCH_FTESECURITY_GUA,Number of FTE security guards,School Support
1825,1826,BRF,SCH_FTESERVICES_NUR,Number of FTE nurses,School Support
1826,1827,BRG,SCH_FTESERVICES_PSY,Number of FTE psychologists,School Support
1827,1828,BRH,SCH_FTESERVICES_SOC,Number of FTE social workers,School Support
1828,1829,BRI,SCH_JJTYPE,Justice Facility Type,Justice Facility
1829,1830,BRJ,SCH_JJSYDAYS,Days in Regular School Year at Justice Facility,Justice Facility
1830,1831,BRK,SCH_JJHOURS,Justice Facility Educational Program Hours per...,Justice Facility
1831,1832,BRL,SCH_JJPART_LT15,Students who participated in credit granting e...,Justice Facility
1832,1833,BRM,SCH_JJPART_15T30,Students who participated in credit granting e...,Justice Facility
1833,1834,BRN,SCH_JJPART_31T90,Students who participated in credit granting e...,Justice Facility
1834,1835,BRO,SCH_JJPART_91T180,Students who participated in credit granting e...,Justice Facility
1835,1836,BRP,SCH_JJPART_OV180,Students who participated in credit granting e...,Justice Facility

**Note:**  For cell values in the school data frame, negative numbers have special meanings as follows:  
-2 means small cell values,  
-5 means there is an action plan (next survey),  
-6 Force Certified (missing data),  
-7 System error,  
-8 EDFacts Missing Data,  
-9 means not applicable / skipped

In [13]:
# print(len(school_data[school_data["LEA_STATE_NAME"] == "CALIFORNIA"]))
nul_vals = [-2,-5,-6,-7,-8,-9, '-2', '-5', '-6','-7','-8','-9']
for (columnName, columnData) in school_data.iteritems():
    continue
     #print(round(len(school_data[columnName][school_data[columnName].isin(nul_vals)])/school_data.shape[0], 3), columnName);

In [11]:
nul_vals = [-2,-5,-6,-7,-8,-9, '-2', '-5', '-6','-7','-8','-9']
# for (columnName, columnData) in school_data.iteritems():
column = "SCH_JJTYPE"
print(school_data[column].unique())
#print(school_data[column][~school_data[column].isin(nul_vals)])

[-7 -9 '-9' '-7' 'Both' 'Post' 'Pre']

In [26]:
def percentage_of_students(school_layout, school_data,layout_a_start,layout_a_stop):
    enrollment = []
    np.seterr(divide = 'ignore')
    enroll_categories = range(layout_a_start,layout_a_stop+1,1)
    enrollment_vals = np.empty([len(enroll_categories)*len(school_data)])
    enrollment_vals.shape = [len(enroll_categories),len(school_data)]
    for i in range(len(enroll_categories)):
        j = enroll_categories[i]
        print(school_layout['Field_Description'][school_layout['Order']==j].values[0])
        enrollment.append(str(school_layout['Field_Name'][school_layout['Order']==j].values[0]))
        nul_bool = school_data[enrollment[-1]].isin(nul_vals)
        value = np.array(school_data[enrollment[-1]])
        value[nul_bool] = 0
        if i == 0:
            enrollment_vals[0] = value
        else:
            enrollment_vals[i] = value
    return(enrollment_vals)

enrollment = percentage_of_students(school_layout,school_data,56,71)
suspensions = percentage_of_students(school_layout,school_data,822,837)
suspensions = np.array(suspensions, dtype=float)
percentages = suspensions/enrollment
percentages = np.nan_to_num(percentages)
print('\n\nPERCENT GROUP SUSPENDED:\n',percentages)
print('\n\nAVERAGE NUMBER OF STUDENTS SUSPENDED IN AN AVERAGE SCHOOL:\n',np.round(np.mean(suspensions,axis=1),3))
print('\n\nAVERAGE NUMBER OF STUDENTS IN AN AVERAGE SCHOOL:\n',np.round(np.mean(enrollment,axis=1),3))
print('\n\nAVERAGE PERCENTAGE OF STUDENTS SUSPENDED IN AN AVERAGE SCHOOL:\n',np.round(np.mean(suspensions,axis=1)/np.mean(enrollment,axis=1),3))

Overall Student Enrollment: Hispanic Male
Overall Student Enrollment: Hispanic Female
Overall Student Enrollment: American Indian/Alaska Native Male
Overall Student Enrollment: American Indian/Alaska Native Female
Overall Student Enrollment: Asian Male
Overall Student Enrollment: Asian Female
Overall Student Enrollment: Native Hawaiian/Pacific Islander Male
Overall Student Enrollment: Native Hawaiian/Pacific Islander Female
Overall Student Enrollment: Black Male
Overall Student Enrollment: Black Female
Overall Student Enrollment: White Male
Overall Student Enrollment: White Female
Overall Student Enrollment: Two or More Races Male
Overall Student Enrollment: Two or More Races Female
Overall Student Enrollment: Calculated Male Total
Overall Student Enrollment: Calculated Female Total
Students without disabilities who received only one out-of-school suspension: Hispanic Male
Students without disabilities who received only one out-of-school suspension: Hispanic Female
Students without disabilities who received only one out-of-school suspension: American Indian/Alaska Native Male
Students without disabilities who received only one out-of-school suspension: American Indian/Alaska Native Female
Students without disabilities who received only one out-of-school suspension: Asian Male
Students without disabilities who received only one out-of-school suspension: Asian Female
Students without disabilities who received only one out-of-school suspension: Native Hawaiian/Pacific Islander Male
Students without disabilities who received only one out-of-school suspension: Native Hawaiian/Pacific Islander Female
Students without disabilities who received only one out-of-school suspension: Black Male
Students without disabilities who received only one out-of-school suspension: Black Female
Students without disabilities who received only one out-of-school suspension: White Male
Students without disabilities who received only one out-of-school suspension: White Female
Students without disabilities who received only one out-of-school suspension: Two or More Races Male
Students without disabilities who received only one out-of-school suspension: Two or More Races Female
Total number of students without disabilities who received only one out-of-school suspension: Calculated Male Total
Total number of students without disabilities who received only one out-of-school suspension: Calculated Female Total


PERCENT GROUP SUSPENDED:
 [[ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.12727273]
 ...,
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.0952381
   0.12727273]
 [ 0.          0.          0.         ...,  0.          0.22222222
   0.07476636]]


AVERAGE NUMBER OF STUDENTS SUSPENDED IN AN AVERAGE SCHOOL:
 [ 2.049  1.05   0.141  0.08   0.172  0.059  0.042  0.022  2.923  1.963
  3.006  1.237  0.387  0.208  8.72   4.618]


AVERAGE NUMBER OF STUDENTS IN AN AVERAGE SCHOOL:
 [  69.33    65.942    2.961    2.831   13.347   12.798    1.167    1.1
   41.414   39.594  132.263  123.844    9.291    8.967  269.774  255.075]


AVERAGE PERCENTAGE OF STUDENTS SUSPENDED IN AN AVERAGE SCHOOL:
 [ 0.03   0.016  0.048  0.028  0.013  0.005  0.036  0.02   0.071  0.05
  0.023  0.01   0.042  0.023  0.032  0.018]

/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:23: RuntimeWarning: invalid value encountered in true_divide

In [43]:
percentages[:,38196]

array([ 0.04878049,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.05714286,  0.        ,
        0.0104712 ,  0.00260756,  0.06896552,  0.0625    ,  0.01550388,
        0.00440044])